#!/usr/bin/env bash

# Script that transfers a file from client to a server

if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

file_path=$1
server_ip=$2
username=$3
key_path=$4

scp -o "StrictHostKeyChecking no" -i $key_path $file_path $username@$server_ip:~/
