#!/usr/bin/env bash
#prints a string 10 times
x=0
while [ $x != 10 ]
do
  if [ $x = 3 ]
  then
    echo "bad luck"
  elif [ $x = 7 ]
  then
    echo "good luck"
  else
    echo "Holberton School"
  fi
  x=$(( x + 1 ))
done
