#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes.
# Displays hours from 0 to 12
# Displays minutes from 1 to 59

h=0
while [ $h -le 12 ]
do
    echo "Hour: $h"
    m=1
    while [ $m -lt 60 ]
    do 
        echo "$m"
        ((m++))
    done
    ((h++))
done

